// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzspvdtdrsyajtkjplmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6c3B2ZHRkcnN5YWp0a2pwbG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDMwNDksImV4cCI6MjA2NjAxOTA0OX0.ulqB6a3BAvUu1z--mpAhhBHwjlziXDQ37uHEWEMSo8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);